### ISSUE TITLE
Revisioning

### ISSUE THREAD

**Issue by arvai** [arvai/trierhu#47]
If I run a gulp build in PROD mode and after in DEV mode, Twig still use the previously created manifest files (so it use the versioned stuff, however I build in DEV mode)

**Comment by szhajdu** [comment]
You can manually delete the rev-manifest.json file from /static/build folder. The backend use this file for the version configuration. 

Solution: create a "clean" task in gulpfile and remove the generated files.

**Comment by szhajdu** [comment]
PR has been created.

**Comment by arvai** [comment]
Thanks.
